name: My GitHub actions
on: push
jobs:
    pytest:
        name: pytest
        runs-on: ubuntu-latest
        steps:
            - name: Check Out
              uses: actions/checkout@v3
            - name: Python Setup
              uses: actions/setup-python@v4
              with:
                python-version: 3.10.*
            - name: Setup Environment
              run: pip install -r requirements.txt
            - name: Run Test
              run: pytest test.py -v



